name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 44.224.249.124
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: backend/
        server-dir: /public_html/api-delivery/
        exclude: '**/.git*'
